// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import '.env';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: apiKey1,
    appId: '1:100051266786:web:d502e9027901e723ae82bb',
    messagingSenderId: '100051266786',
    projectId: 'atlas-23',
    authDomain: 'atlas-23.firebaseapp.com',
    storageBucket: 'atlas-23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: apiKey2,
    appId: '1:100051266786:android:c5c55979451da47fae82bb',
    messagingSenderId: '100051266786',
    projectId: 'atlas-23',
    storageBucket: 'atlas-23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: apiKey3,
    appId: '1:100051266786:ios:179eb4a7ce8f6a4cae82bb',
    messagingSenderId: '100051266786',
    projectId: 'atlas-23',
    storageBucket: 'atlas-23.appspot.com',
    iosClientId: '100051266786-n3387sduccv2ftjeghqmamf0649u84fq.apps.googleusercontent.com',
    iosBundleId: 'com.example.v01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: apiKey4,
    appId: '1:100051266786:ios:179eb4a7ce8f6a4cae82bb',
    messagingSenderId: '100051266786',
    projectId: 'atlas-23',
    storageBucket: 'atlas-23.appspot.com',
    iosClientId: '100051266786-n3387sduccv2ftjeghqmamf0649u84fq.apps.googleusercontent.com',
    iosBundleId: 'com.example.v01',
  );
}
